version: "3.5"
services:

  ds-provider:
    container_name: ds-provider
    image: caparicioesd/rainbow:latest
    platform: linux/arm64/v8
    restart: on-failure
    env_file:
      - ./../.env.core.provider
    depends_on:
      - db-provider
    ports:
      - "1234:1234"
    command: [ "provider", "start" ]


  ds-provider-setup:
    container_name: ds-provider-setup
    image: caparicioesd/rainbow:latest
    platform:  linux/arm64/v8
    restart: on-failure
    env_file:
      - ./../.env.core.provider
    depends_on:
      - db-provider
    command: [ "provider", "setup" ]

  db-provider:
    container_name: "db-provider"
    image: "postgres"
    restart: always
    environment:
      POSTGRES_PASSWORD: ds_core_provider_db
      POSTGRES_USER: ds_core_provider_db
      POSTGRES_DB: ds_core_provider_db
    ports:
      - "5433:5432"

  ds-consumer:
    container_name: ds-consumer
    image: caparicioesd/rainbow:latest
    platform:  linux/arm64/v8
    restart: on-failure
    depends_on:
      - db-consumer
    env_file:
      - ./../.env.core.consumer
    ports:
      - "1235:1235"
    command: [ "consumer", "start" ]

  ds-consumer-setup:
    container_name: ds-consumer-setup
    image: caparicioesd/rainbow:latest
    platform:  linux/arm64/v8
    restart: on-failure
    depends_on:
      - db-consumer
    env_file:
      - ./../.env.core.consumer
    command: [ "consumer", "setup" ]

  db-consumer:
    container_name: "db-consumer"
    image: "postgres"
    restart: always
    environment:
      POSTGRES_PASSWORD: ds_core_consumer_db
      POSTGRES_USER: ds_core_consumer_db
      POSTGRES_DB: ds_core_consumer_db
    ports:
      - "5434:5432"